// ============================================================
// COMPONENT: RejectionRecovery
// OWNER: Track A (Frontend & UX)
// FRAME: 7 — Status Detection and Rejection Recovery
// DESCRIPTION: Shown when manager rejects the trip. Mascot
//   uses empathetic tone to explain the rejection reason, then
//   immediately offers a compliant alternative bundle.
//
//   The alternative is generated by calling /api/trips/[id]/bundles
//   with a constraint: {maxHotelNightlyUsd: policyCapUsd}.
//
// PROPS:
//   tripId: string
//   rejectionReason: string
//   policyCapUsd: number
// ============================================================

// TODO: "use client"
// TODO: import { useState, useEffect } from "react"
// TODO: import { useMascot } from "@/hooks/useMascot"
// TODO: import { BundleCard } from "@/components/trip/BundleCard"

// TODO: export function RejectionRecovery({ tripId, rejectionReason, policyCapUsd }) {
//   // Mascot: say(`I understand — the manager flagged the hotel cost.
//   //   Here's a fully compliant option that stays under $${policyCapUsd}/night.`, "empathetic")
//   // Fetch compliant alternative bundle
//   // Show single BundleCard with the alternative
//   // "Submit for Re-approval" button
// }
